name: Publish to Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src -c Release --no-restore

    - name: Test
      run: dotnet test src -c Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack src -c Release --no-build -p:PublicRelease=true

    - name: Publish
      run: dotnet nuget push bin\Release\JsonServices*.nupkg -k "${{ secrets.NUGET_JSON_SERVICES_API_TOKEN }}" -s https://api.nuget.org/v3/index.json
